### ISSUE TITLE
Do not import modules using an absolute path 

### ISSUE THREAD

**Issue by MUDITJAINN** [TECHOUS/codemash#112]
In the main.js file - Do not import modules using an absolute path 
Avoiding absolute path imports ensures that your project remains flexible, portable, and maintainable across different environments and configurations.
@GauravWalia19  please assign this issue to me under hactoberfest2024

**Comment by GauravWalia19** [comment]
I don't feel its a big issue to fix here, please read the contributing guidelines for contributing correctly
